# Generated by Django 4.2.16 on 2024-11-19 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='书籍名')),
                ('description', models.CharField(max_length=250, verbose_name='书籍简介')),
                ('image', models.ImageField(upload_to='book/images/', verbose_name='书籍封面')),
                ('url', models.URLField(blank=True, verbose_name='书籍资源链接')),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍',
            },
        ),
    ]
